"""empty message

Revision ID: 2ba8bf23251e
Revises: c88e5cc18fe5
Create Date: 2018-09-19 09:37:38.634736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ba8bf23251e'
down_revision = 'c88e5cc18fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
