"""empty message

Revision ID: c88e5cc18fe5
Revises: 623dcb6e2c3c
Create Date: 2018-09-19 09:20:56.133863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88e5cc18fe5'
down_revision = '623dcb6e2c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mail', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'users', ['mail'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mail')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
